#服务端口
server:
  port: 8082

# 数据库密码加密配置
jasypt:
  encryptor:
    password: mypassword

#数据库连接配置
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springboot_demo?characterEncoding=UTF-8
        username: root
        password: ENC(7ZWWzPKyjk1kB8SEKTSFTpsCiHtoxsKM) # 启动类配置注解 @EnableEncryptableProperties 以启动该功能
#      使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
# 配置redis
    redis:
     # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接密码（默认为空）
      password:
      # Redis服务器端口
      port: 6379
    # 连接超时时间（毫秒）
      timeout: 0
      #Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
      database: 0
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
         # 连接池中的最小空闲连接
        min-idle: 0


# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.allan.lockdemo.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql

#控制台输入sql信息，日志级别：debug
debug: true
logging:
  level:
    com.allan.lockdemo.mapper: debug  # 打印mapper下的所有SQL








